const coaches = [
  // === MALAYSIA ===
  {
    name: "Coach Hafiz Rahman",
    slug: "coach-hafiz-rahman",
    bio: "Certified pickleball coach with 5+ years of experience. Former national badminton player who transitioned to pickleball. Specializes in beginner-to-intermediate training with a focus on proper technique and footwork.",
    certifications: ["IPTPA Level 2", "MPA Certified Coach"],
    experience_years: 5,
    hourly_rate: 120,
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    phone: "+6012-111 2222",
    email: "hafiz@pickleball.my",
    is_premium: true,
    verified: true,
  },
  {
    name: "Coach Sarah Lim",
    slug: "coach-sarah-lim",
    bio: "IPTPA Level 1 certified coach specializing in women's pickleball and senior players. Patient, encouraging teaching style. Also coaches kids aged 8-15.",
    certifications: ["IPTPA Level 1", "First Aid Certified"],
    experience_years: 3,
    hourly_rate: 90,
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    phone: "+6016-333 4444",
    email: "sarah@pickledink.my",
    is_premium: true,
    verified: true,
  },
  {
    name: "Coach Wilson Ng",
    slug: "coach-wilson-ng",
    bio: "Competitive pickleball player with tournament wins across Malaysia and Singapore. Teaches advanced strategy, tournament preparation, and doubles tactics. High-intensity training sessions.",
    certifications: ["IPTPA Level 2", "PPR Certified"],
    experience_years: 4,
    hourly_rate: 150,
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    phone: "+6012-987 6543",
    email: "wilson.ng@pickleball.my",
    is_premium: true,
    verified: true,
  },
  {
    name: "Coach Azman Yusof",
    slug: "coach-azman-yusof",
    bio: "Kuching's premier pickleball coach. Passionate about growing the sport in East Malaysia. Teaches all ages and skill levels with a fun, community-focused approach. Free intro sessions for first-timers.",
    certifications: ["MPA Certified Coach"],
    experience_years: 3,
    hourly_rate: 80,
    city: "Kuching",
    state: "Sarawak",
    country: "Malaysia",
    phone: "+6013-555 6666",
    email: "azman@picklekch.my",
    is_premium: true,
    verified: true,
  },
  {
    name: "Coach Priya Devi",
    slug: "coach-priya-devi",
    bio: "Penang-based pickleball coach. Specializes in doubles strategy and partner communication. Also runs corporate team-building pickleball sessions for companies in Penang.",
    certifications: ["IPTPA Level 1"],
    experience_years: 2,
    hourly_rate: 100,
    city: "George Town",
    state: "Penang",
    country: "Malaysia",
    phone: "+6012-777 8888",
    email: "priya@pickleballpenang.my",
    is_premium: false,
    verified: true,
  },
  {
    name: "Coach Jason Tan",
    slug: "coach-jason-tan",
    bio: "Singapore-to-JB pickleball coach. Teaches on both sides of the causeway. Tournament-level coaching with focus on mental game and match strategy.",
    certifications: ["IPTPA Level 3", "PPR Pro Certified"],
    experience_years: 6,
    hourly_rate: 180,
    city: "Johor Bahru",
    state: "Johor",
    country: "Malaysia",
    phone: "+6019-222 3333",
    email: "jason@pickleballsg.com",
    is_premium: true,
    verified: true,
  },

  // === SINGAPORE ===
  {
    name: "Coach Marcus Tan",
    slug: "coach-marcus-tan",
    bio: "Singapore's #1 ranked pickleball coach. Former tennis coach who switched to pickleball in 2020. Trains competitive players for international tournaments. Also runs popular group clinics.",
    certifications: ["IPTPA Level 3", "Tennis Australia Certified"],
    experience_years: 8,
    hourly_rate: 200,
    city: "Singapore",
    state: "Central",
    country: "Singapore",
    phone: "+65 9123 4567",
    email: "marcus@sgpickleball.sg",
    is_premium: true,
    verified: true,
  },

  // === USA ===
  {
    name: "Coach Dave Pickle Pro",
    slug: "coach-dave-pickle-pro",
    bio: "Professional pickleball instructor based in Los Angeles. Teaches at Venice Beach and surrounding courts. Known for making pickleball accessible to everyone — 'If you can walk, you can pickle.'",
    certifications: ["IPTPA Level 2", "USA Pickleball Ambassador"],
    experience_years: 7,
    hourly_rate: 75,
    city: "Los Angeles",
    state: "California",
    country: "United States",
    phone: "+1-310-555-0100",
    email: "dave@pickleballpro.com",
    website: "https://pickleballpro.com",
    is_premium: false,
    verified: true,
  },
];

module.exports = { coaches };
