const courts = [
  // =============================================
  // MALAYSIA (15 courts)
  // =============================================
  {
    name: "Kenanga City Pickleball Stadium",
    slug: "kenanga-city-pickleball-stadium",
    address: "Kenanga City, Jalan Gelugor, Pudu",
    city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia",
    lat: 3.1265, lng: 101.6980,
    indoor: true, court_count: 12, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "pro_shop", "showers", "cafe", "equipment_rental"],
    phone: "+603-9285 8888", website: "https://kenangacity.com.my",
    description: "Malaysia's largest indoor pickleball facility with 12 professional-grade courts. Pro shop on site, coaching available, and regular tournaments.",
    is_premium: true, verified: true,
  },
  {
    name: "Pickleball Hub Mont Kiara",
    slug: "pickleball-hub-mont-kiara",
    address: "1 Mont Kiara Mall, Jalan Kiara",
    city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia",
    lat: 3.1690, lng: 101.6520,
    indoor: true, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    phone: "+6012-345 6789",
    description: "Popular pickleball hub inside 1 Mont Kiara mall. 6 indoor courts with air-conditioning. Beginner classes every weekend.",
    is_premium: true, verified: true,
  },
  {
    name: "Kuching Pickleball Centre",
    slug: "kuching-pickleball-centre",
    address: "Jalan Stampin, Kuching",
    city: "Kuching", state: "Sarawak", country: "Malaysia",
    lat: 1.5200, lng: 110.3500,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+6082-456 789",
    description: "Kuching's first dedicated pickleball centre. Open-air courts with night lighting. Growing community of 200+ regular players.",
    is_premium: true, verified: true,
  },
  {
    name: "Penang Pickleball Arena",
    slug: "penang-pickleball-arena",
    address: "Jalan Sultan Azlan Shah, Bayan Lepas",
    city: "George Town", state: "Penang", country: "Malaysia",
    lat: 5.3300, lng: 100.2800,
    indoor: true, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "pro_shop", "cafe"],
    phone: "+604-678 9012",
    description: "Penang's premier pickleball facility with 8 indoor courts. Hosts the annual Penang Open tournament.",
    is_premium: true, verified: true,
  },
  {
    name: "JB Pickleball Club",
    slug: "jb-pickleball-club",
    address: "Taman Sutera Utama, Skudai",
    city: "Johor Bahru", state: "Johor", country: "Malaysia",
    lat: 1.5500, lng: 103.6600,
    indoor: false, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+6016-789 0123", website: "https://jbpickleball.my",
    description: "JB's largest pickleball club with 6 courts. Strong community with weekly social play and competitive leagues. Popular with Singapore players just across the causeway.",
    is_premium: false, verified: true,
  },
  {
    name: "Kota Kinabalu Pickleball Courts",
    slug: "kota-kinabalu-pickleball-courts",
    address: "Likas Sports Complex, Jalan Punat Tanah",
    city: "Kota Kinabalu", state: "Sabah", country: "Malaysia",
    lat: 5.9900, lng: 116.1100,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    phone: "+6088-345 678",
    description: "4 outdoor pickleball courts within the Likas Sports Complex. Open to public with hourly rates. Coaching available on Saturdays.",
    verified: true,
  },
  {
    name: "Desa ParkCity Pickleball Courts",
    slug: "desa-parkcity-pickleball",
    address: "The Waterfront, Desa ParkCity",
    city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia",
    lat: 3.1900, lng: 101.6300,
    indoor: false, court_count: 3, has_lights: false, surface_type: "hard",
    amenities: ["parking", "cafe"],
    description: "Community courts at Desa ParkCity's Waterfront. Free for residents, small fee for visitors. Great weekend vibe with nearby cafes.",
    verified: false,
  },
  {
    name: "Ipoh Pickleball Centre",
    slug: "ipoh-pickleball-centre",
    address: "Jalan Raja Dr Nazrin Shah, Ipoh",
    city: "Ipoh", state: "Perak", country: "Malaysia",
    lat: 4.6000, lng: 101.0800,
    indoor: true, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+605-789 0123",
    description: "Ipoh's indoor pickleball centre. Air-conditioned with 4 courts. Beginner-friendly with paddle rental available.",
    verified: false,
  },
  {
    name: "Melaka Pickleball Court",
    slug: "melaka-pickleball-court",
    address: "Melaka International Bowling Centre, Jalan Tun Abdul Razak",
    city: "Melaka", state: "Melaka", country: "Malaysia",
    lat: 2.2050, lng: 102.2560,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "cafe", "equipment_rental"],
    phone: "+606-292 1234",
    description: "Pickleball courts inside Melaka International Bowling Centre. 3 indoor courts. Equipment rental available.",
    verified: false,
  },
  {
    name: "Setia Alam Pickleball",
    slug: "setia-alam-pickleball",
    address: "Setia Alam Sports Complex, Seksyen U13",
    city: "Shah Alam", state: "Selangor", country: "Malaysia",
    lat: 3.0860, lng: 101.4490,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball courts at Setia Alam Sports Complex. 4 outdoor courts with night lighting. Popular with the Shah Alam pickleball community.",
    verified: false,
  },
  {
    name: "Puchong Pickleball Club",
    slug: "puchong-pickleball-club",
    address: "Arena Pickleball, Taman Puchong Utama",
    city: "Puchong", state: "Selangor", country: "Malaysia",
    lat: 3.0000, lng: 101.6200,
    indoor: true, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+6012-333 4444",
    description: "Dedicated pickleball facility in Puchong. 4 air-conditioned indoor courts. Coaching available. Weekly social play sessions.",
    verified: true,
  },
  {
    name: "Cheras Pickleball Centre",
    slug: "cheras-pickleball-centre",
    address: "Cheras Sports Complex, Jalan Lingkaran Tengah 2",
    city: "Cheras", state: "Wilayah Persekutuan", country: "Malaysia",
    lat: 3.1050, lng: 101.7350,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball courts within Cheras Sports Complex. 4 floodlit courts. Open to public. Growing community scene.",
    verified: false,
  },
  {
    name: "Seremban Pickleball",
    slug: "seremban-pickleball",
    address: "Seremban 2 Sports Complex, Jalan S2 C1",
    city: "Seremban", state: "Negeri Sembilan", country: "Malaysia",
    lat: 2.7200, lng: 101.9400,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Indoor pickleball courts at Seremban 2 Sports Complex. 3 courts. Equipment available for beginners.",
    verified: false,
  },
  {
    name: "Kuantan Pickleball Arena",
    slug: "kuantan-pickleball-arena",
    address: "Wisma Belia, Jalan Stadium",
    city: "Kuantan", state: "Pahang", country: "Malaysia",
    lat: 3.8200, lng: 103.3300,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "equipment_rental"],
    phone: "+609-567 8901",
    description: "Pickleball at Wisma Belia Kuantan. 3 indoor courts. Weekly sessions growing the sport on Malaysia's east coast.",
    verified: false,
  },
  {
    name: "Langkawi Pickleball Club",
    slug: "langkawi-pickleball-club",
    address: "Langkawi Sports Complex, Jalan Pandak Mayah",
    city: "Langkawi", state: "Kedah", country: "Malaysia",
    lat: 6.3400, lng: 99.7500,
    indoor: false, court_count: 2, has_lights: false, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball courts at Langkawi Sports Complex. Great for tourists visiting the island. Equipment for hire.",
    verified: false,
  },

  // =============================================
  // SINGAPORE (5 courts)
  // =============================================
  {
    name: "Singapore Pickleball Arena @ Kallang",
    slug: "singapore-pickleball-kallang",
    address: "5 Stadium Drive, Kallang",
    city: "Singapore", state: "Central", country: "Singapore",
    lat: 1.3030, lng: 103.8750,
    indoor: true, court_count: 10, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "pro_shop", "cafe", "equipment_rental"],
    phone: "+65 6789 0123", website: "https://sgpickleball.sg",
    description: "Singapore's largest indoor pickleball facility at Kallang. 10 championship-standard courts. Home of the Singapore Pickleball Open.",
    is_premium: true, verified: true,
  },
  {
    name: "OCBC Arena Pickleball Courts",
    slug: "ocbc-arena-pickleball",
    address: "5 Stadium Walk, OCBC Arena",
    city: "Singapore", state: "Central", country: "Singapore",
    lat: 1.3040, lng: 103.8770,
    indoor: true, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    phone: "+65 6345 6789",
    description: "OCBC Arena offers 6 dedicated pickleball courts within Singapore Sports Hub. Top-class facilities with spectator seating for tournaments.",
    verified: true,
  },
  {
    name: "Bukit Batok Pickleball Courts",
    slug: "bukit-batok-pickleball",
    address: "Bukit Batok Sports Hall, 2 Bukit Batok Street 21",
    city: "Singapore", state: "West", country: "Singapore",
    lat: 1.3480, lng: 103.7450,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Community sports hall with 4 pickleball courts in Bukit Batok. Book online via ActiveSG. Popular with families.",
    verified: true,
  },
  {
    name: "Our Tampines Hub Pickleball",
    slug: "our-tampines-hub-pickleball",
    address: "1 Tampines Walk, Our Tampines Hub",
    city: "Singapore", state: "East", country: "Singapore",
    lat: 1.3520, lng: 103.9420,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "restaurant"],
    phone: "+65 6789 4567",
    description: "Pickleball courts at Singapore's largest integrated community hub. Multiple courts available for booking. Great for beginners.",
    verified: false,
  },
  {
    name: "Yio Chu Kang Pickleball Court",
    slug: "yio-chu-kang-pickleball",
    address: "Yio Chu Kang Sports Hall, 210 Ang Mo Kio Ave 9",
    city: "Singapore", state: "North", country: "Singapore",
    lat: 1.3770, lng: 103.8450,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "ActiveSG sports hall with dedicated pickleball court markings. Book online for affordable hourly sessions.",
    verified: false,
  },

  // =============================================
  // USA — California (12 courts)
  // =============================================
  {
    name: "Venice Beach Pickleball Courts",
    slug: "venice-beach-pickleball",
    address: "1800 Ocean Front Walk, Venice",
    city: "Los Angeles", state: "California", country: "United States",
    lat: 33.9850, lng: -118.4730,
    indoor: false, court_count: 8, has_lights: false, surface_type: "hard",
    amenities: ["public_parking"],
    description: "Iconic oceanfront pickleball courts on Venice Beach. Free public courts — first come, first served. Incredible atmosphere. Iconic location near the Venice boardwalk.",
    verified: true,
  },
  {
    name: "Rancho Bernardo Pickleball Courts",
    slug: "rancho-bernardo-pickleball",
    address: "18448 W Bernardo Dr, San Diego",
    city: "San Diego", state: "California", country: "United States",
    lat: 33.0050, lng: -117.0700,
    indoor: false, court_count: 12, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "One of San Diego's largest pickleball facilities with 12 dedicated courts. Very active community with organized play every morning.",
    verified: true,
  },
  {
    name: "Hansen Dam Pickleball Courts",
    slug: "hansen-dam-pickleball",
    address: "11798 Foothill Blvd, Lake View Terrace",
    city: "Los Angeles", state: "California", country: "United States",
    lat: 34.2680, lng: -118.3230,
    indoor: false, court_count: 8, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Popular pickleball destination in the San Fernando Valley. 8 well-maintained courts. Strong community of regular players.",
    verified: true,
  },
  {
    name: "San Francisco Pickleball @ Presidio",
    slug: "sf-presidio-pickleball",
    address: "Presidio Sports Center, 1160 Gorgas Ave, Presidio",
    city: "San Francisco", state: "California", country: "United States",
    lat: 37.7980, lng: -122.4530,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Beautiful pickleball courts inside the Presidio national park. Stunning views. Well-maintained courts with great community.",
    verified: true,
  },
  {
    name: "Palo Alto Pickleball Courts",
    slug: "palo-alto-pickleball",
    address: "Mitchell Park, 3700 Middlefield Rd, Palo Alto",
    city: "Palo Alto", state: "California", country: "United States",
    lat: 37.4180, lng: -122.1280,
    indoor: false, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Mitchell Park has 8 dedicated pickleball courts in the heart of Silicon Valley. Very active community. Drop-in play available.",
    verified: true,
  },
  {
    name: "Orange County Pickleball — Great Park",
    slug: "orange-county-great-park-pickleball",
    address: "8000 Great Park Blvd, Irvine",
    city: "Irvine", state: "California", country: "United States",
    lat: 33.6650, lng: -117.7670,
    indoor: false, court_count: 10, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms", "cafe"],
    description: "10 dedicated pickleball courts at Orange County Great Park. One of OC's most popular pickleball destinations with daily open play.",
    verified: true,
  },
  {
    name: "Sacramento Pickleball — Miller Park",
    slug: "sacramento-miller-park-pickleball",
    address: "2901 Northgate Blvd, Sacramento",
    city: "Sacramento", state: "California", country: "United States",
    lat: 38.6200, lng: -121.4800,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Miller Park in Sacramento offers 6 dedicated pickleball courts. Active community with organized round-robins and open play.",
    verified: false,
  },
  {
    name: "Mountain View Pickleball @ Rengstorff Park",
    slug: "mountain-view-rengstorff-pickleball",
    address: "201 S Rengstorff Ave, Mountain View",
    city: "Mountain View", state: "California", country: "United States",
    lat: 37.3980, lng: -122.0990,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Popular pickleball courts at Rengstorff Park. 6 lighted courts. Strong community of Silicon Valley pickleball players.",
    verified: true,
  },
  {
    name: "Santa Monica Pickleball @ Memorial Park",
    slug: "santa-monica-memorial-park-pickleball",
    address: "1401 Olympic Blvd, Santa Monica",
    city: "Santa Monica", state: "California", country: "United States",
    lat: 34.0190, lng: -118.4770,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Santa Monica's popular pickleball courts at Memorial Park. Great location near the beach. Open play and lessons available.",
    verified: true,
  },
  {
    name: "San Jose Pickleball — Ohlone Park",
    slug: "san-jose-ohlone-pickleball",
    address: "39808 Sundale Dr, San Jose",
    city: "San Jose", state: "California", country: "United States",
    lat: 37.3890, lng: -122.0620,
    indoor: false, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Ohlone Park courts in San Jose. 6 dedicated pickleball courts. Busy community with daily organized play sessions.",
    verified: false,
  },
  {
    name: "Berkeley Pickleball @ Grove Park",
    slug: "berkeley-grove-park-pickleball",
    address: "1930 Grove St, Berkeley",
    city: "Berkeley", state: "California", country: "United States",
    lat: 37.8820, lng: -122.2730,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: [],
    description: "Grove Park in Berkeley with 4 pickleball courts. Free public courts. Popular with students and locals.",
    verified: false,
  },
  {
    name: "Folsom Pickleball @ Livermore Park",
    slug: "folsom-livermore-park-pickleball",
    address: "800 E Natoma St, Folsom",
    city: "Folsom", state: "California", country: "United States",
    lat: 38.6700, lng: -121.1500,
    indoor: false, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "8 dedicated pickleball courts at Livermore Park in Folsom. Large active community with tournaments and social play.",
    verified: false,
  },

  // =============================================
  // USA — Florida (10 courts)
  // =============================================
  {
    name: "The Villages Pickleball Center",
    slug: "the-villages-pickleball-center",
    address: "1400 Paradise Dr, The Villages",
    city: "The Villages", state: "Florida", country: "United States",
    lat: 28.9200, lng: -81.9700,
    indoor: false, court_count: 32, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms", "pro_shop", "cafe", "showers"],
    description: "The pickleball capital of the world. The Villages has over 32 courts and is home to the largest pickleball community on earth. Hundreds of daily players.",
    is_premium: true, verified: true,
  },
  {
    name: "Pickleball Central Florida — Lake Nona",
    slug: "lake-nona-pickleball",
    address: "12050 Narcoossee Rd, Orlando",
    city: "Orlando", state: "Florida", country: "United States",
    lat: 28.3860, lng: -81.2430,
    indoor: false, court_count: 8, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Lake Nona's popular pickleball facility with 8 dedicated courts. Active community in Orlando's fastest-growing neighborhood.",
    verified: true,
  },
  {
    name: "Miami Beach Pickleball @ Collins Park",
    slug: "miami-beach-collins-park-pickleball",
    address: "2100 Collins Ave, Miami Beach",
    city: "Miami", state: "Florida", country: "United States",
    lat: 25.7950, lng: -80.1270,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["restrooms"],
    description: "Premier pickleball courts in Miami Beach's Collins Park. Walking distance to the beach. Very popular with locals and tourists.",
    verified: true,
  },
  {
    name: "Tampa Pickleball @ Williams Park",
    slug: "tampa-williams-park-pickleball",
    address: "2821 N MacDill Ave, Tampa",
    city: "Tampa", state: "Florida", country: "United States",
    lat: 27.9650, lng: -82.4930,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Williams Park offers 6 dedicated pickleball courts. Active community. Drop-in play and organized leagues.",
    verified: true,
  },
  {
    name: "Jacksonville Pickleball — Fletcher Park",
    slug: "jacksonville-fletcher-pickleball",
    address: "8240 Girvin Rd, Jacksonville",
    city: "Jacksonville", state: "Florida", country: "United States",
    lat: 30.3130, lng: -81.5000,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Fletcher Park has 6 lighted pickleball courts in Jacksonville. Strong community with daily open play and skill-level clinics.",
    verified: false,
  },
  {
    name: "Fort Myers Pickleball @ CenturyLink Sports Complex",
    slug: "fort-myers-centurylink-pickleball",
    address: "14100 Six Mile Cypress Pkwy, Fort Myers",
    city: "Fort Myers", state: "Florida", country: "United States",
    lat: 26.5960, lng: -81.8430,
    indoor: false, court_count: 12, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms", "pro_shop"],
    description: "One of Southwest Florida's largest pickleball facilities with 12 courts. Hosts regular tournaments and leagues.",
    verified: false,
  },
  {
    name: "Naples Pickleball Center",
    slug: "naples-pickleball-center",
    address: "3500 Pine Ridge Rd, Naples",
    city: "Naples", state: "Florida", country: "United States",
    lat: 26.2120, lng: -81.7700,
    indoor: false, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms", "pro_shop"],
    description: "Dedicated pickleball facility in the famous Naples retirement community. Active senior and competitive play.",
    verified: false,
  },
  {
    name: "Boca Raton Pickleball @ Sugar Sand Park",
    slug: "boca-raton-sugar-sand-pickleball",
    address: "2100 Collins Ave, Boca Raton",
    city: "Boca Raton", state: "Florida", country: "United States",
    lat: 26.3610, lng: -80.0830,
    indoor: false, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Sugar Sand Park in Boca Raton has 8 dedicated pickleball courts. Large community with organized round-robins.",
    verified: false,
  },
  {
    name: "Sarasota Pickleball @ Arlington Park",
    slug: "sarasota-arlington-park-pickleball",
    address: "2650 Waldemere St, Sarasota",
    city: "Sarasota", state: "Florida", country: "United States",
    lat: 27.3180, lng: -82.5320,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Arlington Park has 6 well-maintained pickleball courts in Sarasota. Very popular with the local retirement community.",
    verified: false,
  },
  {
    name: "Palm Beach Gardens Pickleball",
    slug: "palm-beach-gardens-pickleball",
    address: "10500 N Military Trl, Palm Beach Gardens",
    city: "Palm Beach Gardens", state: "Florida", country: "United States",
    lat: 26.8550, lng: -80.0700,
    indoor: false, court_count: 8, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "8 courts at the Palm Beach Gardens sports complex. Active community with pickleball leagues and social events.",
    verified: false,
  },

  // =============================================
  // USA — Arizona & Nevada (6 courts)
  // =============================================
  {
    name: "Bell Bank Park Pickleball Complex",
    slug: "bell-bank-park-pickleball",
    address: "1 Legacy Dr, Mesa",
    city: "Mesa", state: "Arizona", country: "United States",
    lat: 33.3790, lng: -111.6750,
    indoor: false, court_count: 24, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms", "pro_shop", "cafe", "showers"],
    description: "One of the world's largest pickleball facilities with 24 courts. Bell Bank Park is a premier pickleball destination. Hosts major tournaments.",
    is_premium: true, verified: true,
  },
  {
    name: "Phoenix Pickleball @ Pecos Park",
    slug: "phoenix-pecos-park-pickleball",
    address: "17010 S 48th St, Phoenix",
    city: "Phoenix", state: "Arizona", country: "United States",
    lat: 33.2900, lng: -111.9800,
    indoor: false, court_count: 12, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Pecos Park in Phoenix has 12 dedicated pickleball courts. Large active community with year-round play thanks to the Arizona sun.",
    verified: true,
  },
  {
    name: "Tucson Pickleball @ Udall Park",
    slug: "tucson-udall-park-pickleball",
    address: "7202 E Tanque Verde Rd, Tucson",
    city: "Tucson", state: "Arizona", country: "United States",
    lat: 32.2510, lng: -110.8370,
    indoor: false, court_count: 10, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Udall Park offers 10 dedicated pickleball courts. Very active community with beginners to advanced players. Year-round play.",
    verified: true,
  },
  {
    name: "Las Vegas Pickleball — Sunset Park",
    slug: "las-vegas-sunset-park-pickleball",
    address: "2601 E Sunset Rd, Las Vegas",
    city: "Las Vegas", state: "Nevada", country: "United States",
    lat: 36.1150, lng: -115.1260,
    indoor: false, court_count: 8, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Sunset Park has 8 dedicated pickleball courts in Las Vegas. Very popular with locals. Open play and tournaments available.",
    verified: true,
  },
  {
    name: "Henderson Pickleball @ Civic Center",
    slug: "henderson-civic-center-pickleball",
    address: "350 S Green Valley Pkwy, Henderson",
    city: "Henderson", state: "Nevada", country: "United States",
    lat: 36.0300, lng: -115.0850,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Henderson Civic Center pickleball courts. 6 dedicated courts. Active community in the growing Las Vegas suburb.",
    verified: false,
  },
  {
    name: "Flagstaff Pickleball @ Thorpe Park",
    slug: "flagstaff-thorpe-park-pickleball",
    address: "245 W Thorpe Rd, Flagstaff",
    city: "Flagstaff", state: "Arizona", country: "United States",
    lat: 35.1910, lng: -111.6570,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Thorpe Park in Flagstaff with 4 pickleball courts. Mountain setting with beautiful views. Seasonal play (snow in winter).",
    verified: false,
  },

  // =============================================
  // USA — Texas (8 courts)
  // =============================================
  {
    name: "Chicken N Pickle — Overland Park",
    slug: "chicken-n-pickle-overland-park",
    address: "5901 W 135th St, Overland Park",
    city: "Overland Park", state: "Kansas", country: "United States",
    lat: 38.8820, lng: -94.6500,
    indoor: false, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restaurant", "bar", "pro_shop", "equipment_rental"],
    phone: "+1-913-647-6000", website: "https://chickennpickle.com",
    description: "Famous pickleball-and-chicken chain. 6 outdoor courts, full restaurant + bar. Book courts online. Great for groups and parties.",
    is_premium: true, verified: true,
  },
  {
    name: "Austin Pickleball — Lifetime Austin",
    slug: "austin-lifetime-pickleball",
    address: "11400 Century Oaks Terrace, Austin",
    city: "Austin", state: "Texas", country: "United States",
    lat: 30.4490, lng: -97.7370,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "pro_shop"],
    description: "Life Time Austin offers indoor pickleball with 4 courts. Full athletic club amenities. Membership required.",
    verified: true,
  },
  {
    name: "Dallas Pickleball @ Tietze Park",
    slug: "dallas-tietze-park-pickleball",
    address: "4700 Tietze Dr, Dallas",
    city: "Dallas", state: "Texas", country: "United States",
    lat: 32.8200, lng: -96.7610,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Tietze Park in Dallas has 6 dedicated pickleball courts. Strong community. Open play available daily.",
    verified: true,
  },
  {
    name: "Houston Pickleball — Memorial Park",
    slug: "houston-memorial-park-pickleball",
    address: "6501 Memorial Dr, Houston",
    city: "Houston", state: "Texas", country: "United States",
    lat: 29.7610, lng: -95.4350,
    indoor: false, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Memorial Park in Houston has 8 popular pickleball courts. Large active community. Tournament-level play sessions available.",
    verified: true,
  },
  {
    name: "San Antonio Pickleball @ McAllister Park",
    slug: "san-antonio-mcallister-pickleball",
    address: "13102 Jones Maltsberger Rd, San Antonio",
    city: "San Antonio", state: "Texas", country: "United States",
    lat: 29.5920, lng: -98.4590,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "McAllister Park in San Antonio offers 6 pickleball courts. Active community. Free to play.",
    verified: false,
  },
  {
    name: "Fort Worth Pickleball @ Chisholm Trail Park",
    slug: "fort-worth-chisholm-trail-pickleball",
    address: "3901 SW Loop 820, Fort Worth",
    city: "Fort Worth", state: "Texas", country: "United States",
    lat: 32.6630, lng: -97.3610,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Chisholm Trail Park in Fort Worth with 6 dedicated courts. Growing pickleball community. Drop-in play available.",
    verified: false,
  },
  {
    name: "Plano Pickleball @ Carpenter Park",
    slug: "plano-carpenter-park-pickleball",
    address: "2701 W Spring Creek Pkwy, Plano",
    city: "Plano", state: "Texas", country: "United States",
    lat: 33.0250, lng: -96.7260,
    indoor: false, court_count: 8, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Carpenter Park in Plano has 8 pickleball courts. Very active community in this Dallas suburb. Open play and leagues.",
    verified: false,
  },
  {
    name: "El Paso Pickleball @ Veterans Park",
    slug: "el-paso-veterans-park-pickleball",
    address: "5301 Salem Dr, El Paso",
    city: "El Paso", state: "Texas", country: "United States",
    lat: 31.7750, lng: -106.3870,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Veterans Park in El Paso offers 6 pickleball courts. Active border city community. Year-round play with mild winters.",
    verified: false,
  },

  // =============================================
  // USA — Northeast (8 courts)
  // =============================================
  {
    name: "Central Park Pickleball — NYC",
    slug: "central-park-nyc-pickleball",
    address: "Central Park, Mid-Park at 63rd St (Wollman Rink area)",
    city: "New York", state: "New York", country: "United States",
    lat: 40.7640, lng: -73.9760,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: [],
    description: "Iconic Central Park pickleball courts near Wollman Rink. Free public courts. Very popular — arrive early for a spot!",
    verified: true,
  },
  {
    name: "Brooklyn Pickleball @ Prospect Park",
    slug: "brooklyn-prospect-park-pickleball",
    address: "Parade Ground, Prospect Park, Brooklyn",
    city: "Brooklyn", state: "New York", country: "United States",
    lat: 40.6650, lng: -73.9750,
    indoor: false, court_count: 6, has_lights: false, surface_type: "hard",
    amenities: [],
    description: "Pickleball at Prospect Park's Parade Ground in Brooklyn. 6 courts. Free and very popular with Brooklyn's active community.",
    verified: true,
  },
  {
    name: "Hudson River Pickleball @ Pier 6",
    slug: "hudson-river-pier6-pickleball",
    address: "Pier 6, Brooklyn Bridge Park, Brooklyn",
    city: "Brooklyn", state: "New York", country: "United States",
    lat: 40.6920, lng: -73.9990,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["restrooms"],
    description: "Pickleball with stunning Manhattan skyline views at Pier 6 in Brooklyn Bridge Park. Free courts with incredible backdrop.",
    verified: true,
  },
  {
    name: "Long Island Pickleball @ Eisenhower Park",
    slug: "long-island-eisenhower-pickleball",
    address: "1899 Hempstead Tpke, East Meadow",
    city: "East Meadow", state: "New York", country: "United States",
    lat: 40.7390, lng: -73.5590,
    indoor: false, court_count: 8, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "restrooms"],
    description: "Eisenhower Park on Long Island has 8 dedicated pickleball courts. Large facility with strong community presence.",
    verified: true,
  },
  {
    name: "Boston Pickleball @ Boston Common",
    slug: "boston-common-pickleball",
    address: "139 Tremont St, Boston Common",
    city: "Boston", state: "Massachusetts", country: "United States",
    lat: 42.3550, lng: -71.0650,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: [],
    description: "Pickleball courts on America's oldest public park — Boston Common. Free courts with beautiful historic setting.",
    verified: true,
  },
  {
    name: "Philadelphia Pickleball @ FDR Park",
    slug: "philadelphia-fdr-park-pickleball",
    address: "1500 Pattison Ave, Philadelphia",
    city: "Philadelphia", state: "Pennsylvania", country: "United States",
    lat: 39.9000, lng: -75.1800,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "FDR Park in South Philadelphia has 6 pickleball courts. Large active community. Free to play.",
    verified: false,
  },
  {
    name: "Washington DC Pickleball @ Hains Point",
    slug: "washington-dc-hains-point-pickleball",
    address: "East Potomac Park, 972 Ohio Dr SW",
    city: "Washington", state: "District of Columbia", country: "United States",
    lat: 38.8700, lng: -77.0360,
    indoor: false, court_count: 6, has_lights: false, surface_type: "hard",
    amenities: ["parking"],
    description: "Popular pickleball courts at Hains Point in East Potomac Park. Great views of the DC monuments. Very popular on weekends.",
    verified: true,
  },
  {
    name: "Chicago Pickleball @ Maggie Daley Park",
    slug: "chicago-maggie-daley-pickleball",
    address: "337 E Randolph St, Chicago",
    city: "Chicago", state: "Illinois", country: "United States",
    lat: 41.8820, lng: -87.6190,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["restrooms"],
    description: "Pickleball courts at Maggie Daley Park with iconic views of the Chicago skyline. Free public courts. Very popular summer spot.",
    verified: true,
  },

  // =============================================
  // CANADA (6 courts)
  // =============================================
  {
    name: "Toronto Pickleball @ Ashbridges Bay",
    slug: "toronto-ashbridges-bay-pickleball",
    address: "1561 Lake Shore Blvd E, Toronto",
    city: "Toronto", state: "Ontario", country: "Canada",
    lat: 43.6630, lng: -79.3140,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Popular pickleball courts at Ashbridges Bay on Lake Ontario. Beautiful waterfront location. Active Toronto community.",
    verified: true,
  },
  {
    name: "Vancouver Pickleball @ Stanley Park",
    slug: "vancouver-stanley-park-pickleball",
    address: "Stanley Park, Vancouver Seawall",
    city: "Vancouver", state: "British Columbia", country: "Canada",
    lat: 49.3000, lng: -123.1350,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Beautiful pickleball courts in iconic Stanley Park. Ocean and mountain views. Free courts, very popular with Vancouver players.",
    verified: true,
  },
  {
    name: "Montreal Pickleball @ Jeanne-Mance Park",
    slug: "montreal-jeanne-mance-pickleball",
    address: "Parc Jeanne-Mance, 4400 Park Ave, Montreal",
    city: "Montreal", state: "Quebec", country: "Canada",
    lat: 45.5100, lng: -73.5860,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: [],
    description: "Pickleball courts at Jeanne-Mance Park on Montreal's Plateau. Popular with the diverse Montreal community. Free play.",
    verified: true,
  },
  {
    name: "Calgary Pickleball @ Southland Leisure Centre",
    slug: "calgary-southland-leisure-pickleball",
    address: "2000 Southland Dr SW, Calgary",
    city: "Calgary", state: "Alberta", country: "Canada",
    lat: 50.9650, lng: -114.1150,
    indoor: true, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Southland Leisure Centre in Calgary offers 6 indoor pickleball courts. Year-round play in a full recreational facility.",
    verified: true,
  },
  {
    name: "Ottawa Pickleball @ Brewer Park",
    slug: "ottawa-brewer-park-pickleball",
    address: "151 Brewer Way, Ottawa",
    city: "Ottawa", state: "Ontario", country: "Canada",
    lat: 45.3850, lng: -75.7140,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Brewer Park in Ottawa has 6 popular pickleball courts. Active community. Seasonal play (spring through fall).",
    verified: false,
  },
  {
    name: "Edmonton Pickleball @ Rundle Park",
    slug: "edmonton-rundle-park-pickleball",
    address: "2909 113 Ave NW, Edmonton",
    city: "Edmonton", state: "Alberta", country: "Canada",
    lat: 53.5500, lng: -113.3800,
    indoor: false, court_count: 6, has_lights: true, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Rundle Park in Edmonton has 6 designated pickleball courts. Strong community. Free to play.",
    verified: false,
  },

  // =============================================
  // UNITED KINGDOM (6 courts)
  // =============================================
  {
    name: "Pickleball London @ Canary Wharf",
    slug: "pickleball-london-canary-wharf",
    address: "Crossrail Place, Canary Wharf",
    city: "London", state: "England", country: "United Kingdom",
    lat: 51.5050, lng: -0.0200,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "equipment_rental"],
    phone: "+44-20-7000 1234",
    description: "London's rooftop pickleball courts at Canary Wharf. Stunning city views. Book via app. Coaching and corporate events available.",
    verified: true,
  },
  {
    name: "Bristol Pickleball Club",
    slug: "bristol-pickleball-club",
    address: "Bristol Lawn Tennis Club, Redland Green",
    city: "Bristol", state: "England", country: "United Kingdom",
    lat: 51.4730, lng: -2.5850,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe"],
    phone: "+44-117-000 1234",
    description: "Bristol's dedicated pickleball club with 4 courts. Active community. Coaching and social play available.",
    verified: true,
  },
  {
    name: "Manchester Pickleball @ National Squash Centre",
    slug: "manchester-national-squash-pickleball",
    address: "Rowsley St, Manchester",
    city: "Manchester", state: "England", country: "United Kingdom",
    lat: 53.4740, lng: -2.2200,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at the National Squash Centre in Manchester. 3 courts. Part of the growing UK pickleball scene.",
    verified: false,
  },
  {
    name: "Birmingham Pickleball @ Edgbaston Priory",
    slug: "birmingham-edgbaston-pickleball",
    address: "Pershore Rd, Edgbaston, Birmingham",
    city: "Birmingham", state: "England", country: "United Kingdom",
    lat: 52.4560, lng: -1.9100,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at Edgbaston Priory Club in Birmingham. 4 indoor courts. Premier sports club setting.",
    verified: false,
  },
  {
    name: "Glasgow Pickleball @ Scotstoun",
    slug: "glasgow-scotstoun-pickleball",
    address: "72 Danes Dr, Glasgow",
    city: "Glasgow", state: "Scotland", country: "United Kingdom",
    lat: 55.8710, lng: -4.3180,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Indoor pickleball at Scotstoun Leisure Centre in Glasgow. Growing Scottish pickleball community. Equipment available.",
    verified: false,
  },
  {
    name: "Edinburgh Pickleball @ Meadowbank",
    slug: "edinburgh-meadowbank-pickleball",
    address: "139 London Rd, Edinburgh",
    city: "Edinburgh", state: "Scotland", country: "United Kingdom",
    lat: 55.9560, lng: -3.1650,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball at Meadowbank Sports Centre in Edinburgh. 3 indoor courts. Part of Scotland's growing pickleball community.",
    verified: false,
  },

  // =============================================
  // AUSTRALIA (6 courts)
  // =============================================
  {
    name: "Sydney Pickleball Club",
    slug: "sydney-pickleball-club",
    address: "Perry Park, Maddox St, Alexandria",
    city: "Sydney", state: "NSW", country: "Australia",
    lat: -33.9000, lng: 151.1900,
    indoor: false, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+61-2-8000 1234", website: "https://sydneypickleball.com.au",
    description: "Sydney's largest pickleball club with 6 dedicated courts. All skill levels welcome. Social play Wednesdays and Saturdays.",
    verified: true,
  },
  {
    name: "Melbourne Pickleball @ Albert Park",
    slug: "melbourne-albert-park-pickleball",
    address: "Melbourne Sports & Aquatic Centre, Albert Park",
    city: "Melbourne", state: "VIC", country: "Australia",
    lat: -37.8430, lng: 144.9700,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "equipment_rental"],
    phone: "+61-3-9000 5678",
    description: "Indoor pickleball at MSAC in Albert Park, Melbourne. Premier facility. Active Melbourne pickleball community.",
    verified: true,
  },
  {
    name: "Brisbane Pickleball @ Centenary Pool",
    slug: "brisbane-centenary-pool-pickleball",
    address: "600 Gregory Tce, Spring Hill, Brisbane",
    city: "Brisbane", state: "QLD", country: "Australia",
    lat: -27.4680, lng: 153.0250,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Brisbane's popular pickleball location at Centenary Pool complex. 4 outdoor courts. Strong community in Australia's sunshine state.",
    verified: true,
  },
  {
    name: "Perth Pickleball @ Kings Park",
    slug: "perth-kings-park-pickleball",
    address: "Kings Park Tennis Courts, Fraser Ave, Perth",
    city: "Perth", state: "WA", country: "Australia",
    lat: -31.9610, lng: 115.8350,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["parking", "restrooms"],
    description: "Pickleball courts set within beautiful Kings Park. Stunning views of the Swan River and Perth skyline.",
    verified: false,
  },
  {
    name: "Gold Coast Pickleball",
    slug: "gold-coast-pickleball",
    address: "Gold Coast Regional Sports Centre, 176 Eastern Ave, Carrara",
    city: "Gold Coast", state: "QLD", country: "Australia",
    lat: -28.0120, lng: 153.3550,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at the Gold Coast Regional Sports Centre. Active Gold Coast community with year-round play.",
    verified: false,
  },
  {
    name: "Adelaide Pickleball @ Unley",
    slug: "adelaide-unley-pickleball",
    address: "Unley Tennis Club, 44 Cambridge St, Unley",
    city: "Adelaide", state: "SA", country: "Australia",
    lat: -34.9510, lng: 138.6080,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe"],
    description: "Unley Tennis Club in Adelaide offers 4 dedicated pickleball courts. Growing community in South Australia.",
    verified: false,
  },

  // =============================================
  // NEW ZEALAND (3 courts)
  // =============================================
  {
    name: "Auckland Pickleball @ ASB Tennis Centre",
    slug: "auckland-asb-tennis-pickleball",
    address: "1 Tennis Ln, Parnell, Auckland",
    city: "Auckland", state: "Auckland", country: "New Zealand",
    lat: -36.8560, lng: 174.7750,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe", "equipment_rental"],
    description: "Pickleball at ASB Tennis Centre in Auckland. Premier facility with 4 courts. Active NZ pickleball community.",
    verified: true,
  },
  {
    name: "Christchurch Pickleball @ Hagley Park",
    slug: "christchurch-hagley-park-pickleball",
    address: "Hagley Park Tennis Courts, Christchurch",
    city: "Christchurch", state: "Canterbury", country: "New Zealand",
    lat: -43.5250, lng: 172.6220,
    indoor: false, court_count: 4, has_lights: false, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball at Hagley Park in Christchurch. Beautiful setting with mountain views. Free public courts.",
    verified: false,
  },
  {
    name: "Wellington Pickleball @ Central Park",
    slug: "wellington-central-park-pickleball",
    address: "Central Park Tennis Courts, Brooklyn, Wellington",
    city: "Wellington", state: "Wellington", country: "New Zealand",
    lat: -41.3050, lng: 174.7740,
    indoor: false, court_count: 3, has_lights: false, surface_type: "hard",
    amenities: ["parking"],
    description: "Central Park in Wellington offers pickleball courts with amazing harbour views. Active community.",
    verified: false,
  },

  // =============================================
  // THAILAND (4 courts)
  // =============================================
  {
    name: "Bangkok Pickleball Center",
    slug: "bangkok-pickleball-center",
    address: "Sukhumvit 71, Phra Khanong, Bangkok",
    city: "Bangkok", state: "Bangkok", country: "Thailand",
    lat: 13.7200, lng: 100.5900,
    indoor: true, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "equipment_rental"],
    phone: "+66-2-000 1234",
    description: "Bangkok's dedicated indoor pickleball facility. 6 air-conditioned courts. Popular with expats and locals. Coaching in English and Thai.",
    verified: true,
  },
  {
    name: "Phuket Pickleball Club",
    slug: "phuket-pickleball-club",
    address: "Thanyapura Sports & Health Resort, Thalang, Phuket",
    city: "Phuket", state: "Phuket", country: "Thailand",
    lat: 7.9990, lng: 98.3610,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "equipment_rental", "swimming_pool"],
    phone: "+66-76-000 5678",
    description: "Pickleball at Thanyapura resort in Phuket. 4 indoor courts in a tropical paradise. Popular with tourists. Coaching available.",
    verified: true,
  },
  {
    name: "Pattaya Pickleball @ Horseshoe Point",
    slug: "pattaya-horseshoe-point-pickleball",
    address: "202 Moo 6, Pattaya City",
    city: "Pattaya", state: "Chonburi", country: "Thailand",
    lat: 12.9200, lng: 100.9000,
    indoor: true, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    description: "Pickleball at Horseshoe Point Resort in Pattaya. 3 indoor courts. Resort setting with great amenities.",
    verified: false,
  },
  {
    name: "Chiang Mai Pickleball",
    slug: "chiang-mai-pickleball",
    address: "Chiang Mai Sports Complex, 199 Moo 5, Mae Hia",
    city: "Chiang Mai", state: "Chiang Mai", country: "Thailand",
    lat: 18.7800, lng: 98.9750,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Indoor pickleball at Chiang Mai Sports Complex. Growing community in northern Thailand. Popular with expats.",
    verified: false,
  },

  // =============================================
  // INDONESIA (4 courts)
  // =============================================
  {
    name: "Jakarta Pickleball @ GBK",
    slug: "jakarta-pickleball-gbk",
    address: "Gelora Bung Karno Complex, Senayan, Jakarta",
    city: "Jakarta", state: "DKI Jakarta", country: "Indonesia",
    lat: -6.2200, lng: 106.8000,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "equipment_rental"],
    description: "Pickleball courts within the iconic GBK sports complex in Jakarta. Growing community with weekend tournaments.",
    verified: true,
  },
  {
    name: "Bali Pickleball @ Canggu",
    slug: "bali-canggu-pickleball",
    address: "FINNS Rec Club, Jl. Pantai Berawa, Canggu, Bali",
    city: "Canggu", state: "Bali", country: "Indonesia",
    lat: -8.6630, lng: 115.1460,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "cafe", "restaurant", "equipment_rental"],
    phone: "+62-361-000 1234",
    description: "Pickleball at FINNS Rec Club in Canggu, Bali. Tropical beachside courts. Popular with digital nomads and tourists.",
    verified: true,
  },
  {
    name: "Surabaya Pickleball Club",
    slug: "surabaya-pickleball-club",
    address: "GOR Pancasila, Jl. Pandegiling, Surabaya",
    city: "Surabaya", state: "East Java", country: "Indonesia",
    lat: -7.2650, lng: 112.7400,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball at Pancasila Sports Hall. Active Surabaya community with regular social play sessions.",
    verified: false,
  },
  {
    name: "Ubud Pickleball Bali",
    slug: "ubud-pickleball-bali",
    address: "Ubud Sports Centre, Jl. Raya Ubud, Bali",
    city: "Ubud", state: "Bali", country: "Indonesia",
    lat: -8.5070, lng: 115.2650,
    indoor: false, court_count: 2, has_lights: false, surface_type: "hard",
    amenities: ["parking", "cafe"],
    description: "Pickleball in Bali's cultural heart — Ubud. Rice terrace views. Growing scene. Equipment available for rent.",
    verified: false,
  },

  // =============================================
  // JAPAN (4 courts)
  // =============================================
  {
    name: "Tokyo Pickleball @ Ariake Tennis Park",
    slug: "tokyo-ariake-pickleball",
    address: "3-1 Ariake, Koto City, Tokyo",
    city: "Tokyo", state: "Tokyo", country: "Japan",
    lat: 35.6420, lng: 139.7950,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers"],
    description: "Pickleball at Ariake Tennis Park — venue of the 2020 Tokyo Olympics. Japan's premier pickleball location. Hosting Tokyo's growing pickleball community.",
    verified: true,
  },
  {
    name: "Osaka Pickleball Club",
    slug: "osaka-pickleball-club",
    address: "Osaka Tennis Center, 2-2-55 Nanko-Naka, Suminoe-ku, Osaka",
    city: "Osaka", state: "Osaka", country: "Japan",
    lat: 34.6330, lng: 135.4200,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers"],
    description: "Pickleball at the Osaka Tennis Center. 4 courts in Japan's second city. Growing community with regular sessions.",
    verified: true,
  },
  {
    name: "Nagoya Pickleball Courts",
    slug: "nagoya-pickleball-courts",
    address: "Nagoya City Sports Center, 918 Oto-cho, Mizuho-ku, Nagoya",
    city: "Nagoya", state: "Aichi", country: "Japan",
    lat: 35.1250, lng: 136.9220,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Indoor pickleball at Nagoya's comprehensive sports center. Growing interest in Japan's pickleball scene.",
    verified: false,
  },
  {
    name: "Kyoto Pickleball @ Shimogamo",
    slug: "kyoto-shimogamo-pickleball",
    address: "Shimogamo Sports Center, 74 Shimogamo-cho, Sakyo-ku, Kyoto",
    city: "Kyoto", state: "Kyoto", country: "Japan",
    lat: 35.0400, lng: 135.7700,
    indoor: true, court_count: 2, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball at Shimogamo Sports Center in Kyoto. 2 indoor courts. Beautiful historic city setting.",
    verified: false,
  },

  // =============================================
  // SOUTH KOREA (3 courts)
  // =============================================
  {
    name: "Seoul Pickleball @ Jamsil Sports Complex",
    slug: "seoul-jamsil-pickleball",
    address: "Jamsil Sports Complex, 10 Jamsil-dong, Songpa-gu, Seoul",
    city: "Seoul", state: "Seoul", country: "South Korea",
    lat: 37.5120, lng: 127.1000,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers"],
    description: "Pickleball at Seoul's Jamsil Sports Complex — home of the 1988 Olympics. Korea's leading pickleball venue. Growing community.",
    verified: true,
  },
  {
    name: "Busan Pickleball Center",
    slug: "busan-pickleball-center",
    address: "Sajik Sports Complex, 12 Sajik-dong, Dongnae-gu, Busan",
    city: "Busan", state: "Busan", country: "South Korea",
    lat: 35.2000, lng: 129.0550,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball at Sajik Sports Complex in Busan. 3 indoor courts. Active community in Korea's second city.",
    verified: false,
  },
  {
    name: "Incheon Pickleball",
    slug: "incheon-pickleball",
    address: "Incheon Tennis Park, 262 Munhak-dong, Nam-gu, Incheon",
    city: "Incheon", state: "Incheon", country: "South Korea",
    lat: 37.4380, lng: 126.6970,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball at Incheon Tennis Park. 3 courts near Seoul's main international airport. Popular with expats and locals.",
    verified: false,
  },

  // =============================================
  // PHILIPPINES (3 courts)
  // =============================================
  {
    name: "Manila Pickleball @ Rizal Memorial",
    slug: "manila-rizal-memorial-pickleball",
    address: "Rizal Memorial Sports Complex, 1538 Vito Cruz, Manila",
    city: "Manila", state: "Metro Manila", country: "Philippines",
    lat: 14.5650, lng: 120.9920,
    indoor: false, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball at the historic Rizal Memorial Sports Complex in Manila. Active Philippine pickleball community.",
    verified: true,
  },
  {
    name: "Cebu Pickleball Club",
    slug: "cebu-pickleball-club",
    address: "Cebu City Sports Complex, Osmena Blvd, Cebu City",
    city: "Cebu City", state: "Cebu", country: "Philippines",
    lat: 10.3130, lng: 123.8860,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball at Cebu City Sports Complex. Growing community in the Queen City of the South.",
    verified: false,
  },
  {
    name: "Davao Pickleball Courts",
    slug: "davao-pickleball-courts",
    address: "Davao City Sports Complex, J.P. Laurel Ave, Davao City",
    city: "Davao City", state: "Davao", country: "Philippines",
    lat: 7.0790, lng: 125.6130,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball courts at Davao City Sports Complex. Pickleball is growing in Mindanao. Friendly community welcomes all levels.",
    verified: false,
  },

  // =============================================
  // VIETNAM (3 courts)
  // =============================================
  {
    name: "Saigon Pickleball @ Phu Nhuan",
    slug: "saigon-phu-nhuan-pickleball",
    address: "Phu Nhuan Sports Center, 92 Nguyen Huu Tho, HCMC",
    city: "Ho Chi Minh City", state: "HCMC", country: "Vietnam",
    lat: 10.8000, lng: 106.6800,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "equipment_rental"],
    phone: "+84-28-000 1234",
    description: "Saigon's premier indoor pickleball facility. 4 courts at Phu Nhuan Sports Center. Rapidly growing pickleball scene in Vietnam.",
    verified: true,
  },
  {
    name: "Hanoi Pickleball @ My Dinh",
    slug: "hanoi-my-dinh-pickleball",
    address: "My Dinh National Stadium, Tu Liem, Hanoi",
    city: "Hanoi", state: "Hanoi", country: "Vietnam",
    lat: 21.0240, lng: 105.7640,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers"],
    description: "Pickleball at My Dinh National Stadium in Hanoi. Growing community in Vietnam's capital.",
    verified: false,
  },
  {
    name: "Da Nang Pickleball",
    slug: "da-nang-pickleball",
    address: "Tien Son Sports Center, 29 Hai Phong, Da Nang",
    city: "Da Nang", state: "Da Nang", country: "Vietnam",
    lat: 16.0720, lng: 108.2200,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Indoor pickleball at Tien Son Sports Center in Da Nang. Beautiful central Vietnam location. Growing community.",
    verified: false,
  },

  // =============================================
  // INDIA (4 courts)
  // =============================================
  {
    name: "Mumbai Pickleball @ CCI",
    slug: "mumbai-cci-pickleball",
    address: "Cricket Club of India, Brabourne Stadium, Churchgate, Mumbai",
    city: "Mumbai", state: "Maharashtra", country: "India",
    lat: 18.9300, lng: 72.8250,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    description: "Pickleball at the historic Cricket Club of India in the heart of Mumbai. India's premier pickleball location.",
    verified: true,
  },
  {
    name: "Bangalore Pickleball Club",
    slug: "bangalore-pickleball-club",
    address: "Karnataka Badminton Association Stadium, 84/2, Koramangala",
    city: "Bangalore", state: "Karnataka", country: "India",
    lat: 12.9350, lng: 77.6240,
    indoor: true, court_count: 4, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Indoor pickleball in Bangalore's Koramangala district. Active community with regular tournaments in India's tech capital.",
    verified: true,
  },
  {
    name: "Delhi Pickleball Courts",
    slug: "delhi-pickleball-courts",
    address: "Siri Fort Sports Complex, August Kranti Marg, New Delhi",
    city: "New Delhi", state: "Delhi", country: "India",
    lat: 28.5500, lng: 77.2200,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers"],
    description: "Pickleball at Siri Fort Sports Complex in New Delhi. Growing community in India's capital.",
    verified: false,
  },
  {
    name: "Chennai Pickleball @ Nungambakkam",
    slug: "chennai-nungambakkam-pickleball",
    address: "Nungambakkam Tennis Club, 48 College Rd, Chennai",
    city: "Chennai", state: "Tamil Nadu", country: "India",
    lat: 13.0580, lng: 80.2410,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe"],
    description: "Pickleball at Nungambakkam Tennis Club in Chennai. Active community in South India.",
    verified: false,
  },

  // =============================================
  // EUROPE — SPAIN (3 courts)
  // =============================================
  {
    name: "Barcelona Pickleball @ Barcino Tennis",
    slug: "barcelona-barcino-tennis-pickleball",
    address: "Barcino Tennis Club, C/ Dèntol, 73, Cornellà de Llobregat",
    city: "Barcelona", state: "Catalonia", country: "Spain",
    lat: 41.3500, lng: 2.0700,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe", "restaurant"],
    description: "Barcelona's premier pickleball location with 4 dedicated courts at Barcino Tennis Club. Mediterranean's best pickleball scene.",
    verified: true,
  },
  {
    name: "Madrid Pickleball @ Club de Campo",
    slug: "madrid-club-de-campo-pickleball",
    address: "Club de Campo, Ctra. de Castilla, 94, Madrid",
    city: "Madrid", state: "Madrid", country: "Spain",
    lat: 40.4100, lng: -3.7550,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    description: "Pickleball at Club de Campo in Madrid. Premier sports club setting. Growing Spanish pickleball scene.",
    verified: false,
  },
  {
    name: "Costa del Sol Pickleball @ Marbella",
    slug: "marbella-costa-del-sol-pickleball",
    address: "Marbella Tennis Club, Av. de la Fontanilla, Marbella",
    city: "Marbella", state: "Andalusia", country: "Spain",
    lat: 36.5000, lng: -4.8850,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe", "restaurant"],
    description: "Pickleball on the Costa del Sol at Marbella Tennis Club. Sunshine, beaches, and pickleball. Popular with international visitors.",
    verified: false,
  },

  // =============================================
  // EUROPE — FRANCE & GERMANY (4 courts)
  // =============================================
  {
    name: "Paris Pickleball @ Stade Français",
    slug: "paris-stade-francais-pickleball",
    address: "Stade Français, 50 Rue de la Procession, Paris",
    city: "Paris", state: "Île-de-France", country: "France",
    lat: 48.8410, lng: 2.3130,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at Stade Français in Paris. France's leading pickleball venue. Growing community in the City of Light.",
    verified: true,
  },
  {
    name: "Berlin Pickleball @ SCC Berlin",
    slug: "berlin-scc-pickleball",
    address: "SCC Berlin, Waldschulallee 34, Berlin",
    city: "Berlin", state: "Berlin", country: "Germany",
    lat: 52.5100, lng: 13.2500,
    indoor: true, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at SCC Berlin — one of Germany's largest sports clubs. Leading the German pickleball growth.",
    verified: true,
  },
  {
    name: "Munich Pickleball @ MTTC Iphitos",
    slug: "munich-iphtos-pickleball",
    address: "MTTC Iphitos, Hans-Sachs-Str. 2, Munich",
    city: "Munich", state: "Bavaria", country: "Germany",
    lat: 48.1620, lng: 11.5940,
    indoor: false, court_count: 3, has_lights: true, surface_type: "hard",
    amenities: ["parking", "cafe"],
    description: "Pickleball at Germany's oldest tennis club — MTTC Iphitos in Munich. Growing Bavarian pickleball scene.",
    verified: false,
  },
  {
    name: "Nice Pickleball @ Nice Lawn Tennis Club",
    slug: "nice-lawn-tennis-pickleball",
    address: "Nice Lawn Tennis Club, 16 Bd de Stalingrad, Nice",
    city: "Nice", state: "Provence-Alpes-Côte d'Azur", country: "France",
    lat: 43.6900, lng: 7.2800,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe"],
    description: "Pickleball on the French Riviera at Nice Lawn Tennis Club. Stunning Mediterranean setting. Growing French community.",
    verified: false,
  },

  // =============================================
  // MIDDLE EAST — UAE (3 courts)
  // =============================================
  {
    name: "Dubai Pickleball @ Dubai Sports World",
    slug: "dubai-sports-world-pickleball",
    address: "Dubai World Trade Centre, Sheikh Zayed Rd, Dubai",
    city: "Dubai", state: "Dubai", country: "United Arab Emirates",
    lat: 25.2290, lng: 55.2880,
    indoor: true, court_count: 6, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "pro_shop", "equipment_rental"],
    phone: "+971-4-000 1234",
    description: "Dubai's premier pickleball venue with 6 indoor courts at Dubai Sports World. Premium facilities. Rapidly growing UAE pickleball scene.",
    is_premium: true, verified: true,
  },
  {
    name: "Abu Dhabi Pickleball Club",
    slug: "abu-dhabi-pickleball-club",
    address: "Abu Dhabi Country Club, 7th St, Al Rawdah, Abu Dhabi",
    city: "Abu Dhabi", state: "Abu Dhabi", country: "United Arab Emirates",
    lat: 24.4400, lng: 54.3800,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "restaurant"],
    description: "Pickleball at Abu Dhabi Country Club. 4 courts. Premier club setting with full resort amenities.",
    verified: true,
  },
  {
    name: "Doha Pickleball @ Aspire Zone",
    slug: "doha-aspire-pickleball",
    address: "Aspire Zone, Al Shahaniya Rd, Doha",
    city: "Doha", state: "Doha", country: "Qatar",
    lat: 25.2600, lng: 51.4500,
    indoor: true, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    description: "Pickleball at Aspire Zone in Doha — one of the world's premier sports complexes. 4 indoor courts. Growing Qatar community.",
    verified: false,
  },

  // =============================================
  // LATIN AMERICA — BRAZIL & MEXICO (4 courts)
  // =============================================
  {
    name: "São Paulo Pickleball @ Pinheiros",
    slug: "sao-paulo-pinheiros-pickleball",
    address: "Esporte Clube Pinheiros, Rua Rodolpho Villela, 230",
    city: "São Paulo", state: "SP", country: "Brazil",
    lat: -23.5730, lng: -46.6790,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "restaurant"],
    description: "Pickleball at Brazil's most prestigious sports club — Pinheiros. 4 courts leading Brazil's pickleball growth.",
    verified: true,
  },
  {
    name: "Mexico City Pickleball @ Club de Golf México",
    slug: "mexico-city-golf-pickleball",
    address: "Club de Golf México, Pedregal, Mexico City",
    city: "Mexico City", state: "CDMX", country: "Mexico",
    lat: 19.3200, lng: -99.1930,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe", "restaurant"],
    description: "Pickleball at Club de Golf México in the Pedregal district. Growing Mexican pickleball community.",
    verified: false,
  },
  {
    name: "Rio de Janeiro Pickleball @ Lagoa",
    slug: "rio-lagoa-pickleball",
    address: "Lagoa Rodrigo de Freitas, Tennis Courts, Rio de Janeiro",
    city: "Rio de Janeiro", state: "RJ", country: "Brazil",
    lat: -22.9750, lng: -43.1970,
    indoor: false, court_count: 3, has_lights: false, surface_type: "hard",
    amenities: ["parking"],
    description: "Pickleball at Lagoa Rodrigo de Freitas in Rio. Stunning setting with views of Christ the Redeemer. Free courts.",
    verified: false,
  },
  {
    name: "Cancun Pickleball Resort",
    slug: "cancun-pickleball-resort",
    address: "Iberostar Cancun Resort, Blvd. Kukulcan Km 17, Cancun",
    city: "Cancun", state: "Quintana Roo", country: "Mexico",
    lat: 21.1600, lng: -86.8300,
    indoor: false, court_count: 3, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "cafe", "restaurant", "swimming_pool"],
    description: "Pickleball at Iberostar Cancun Resort. Beautiful beachside courts. Popular vacation pickleball destination.",
    verified: false,
  },

  // =============================================
  // CHINA — HONG KONG (2 courts)
  // =============================================
  {
    name: "Hong Kong Pickleball @ Victoria Park",
    slug: "hong-kong-victoria-park-pickleball",
    address: "Victoria Park Tennis Courts, Causeway Bay, Hong Kong",
    city: "Hong Kong", state: "Hong Kong", country: "Hong Kong",
    lat: 22.2820, lng: 114.1880,
    indoor: false, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers"],
    description: "Pickleball at Victoria Park in Causeway Bay. Hong Kong's most popular pickleball location. Very active HK community.",
    verified: true,
  },
  {
    name: "Shenzhen Pickleball Club",
    slug: "shenzhen-pickleball-club",
    address: "Shenzhen Bay Sports Center, Shenzhen",
    city: "Shenzhen", state: "Guangdong", country: "China",
    lat: 22.5270, lng: 113.9500,
    indoor: true, court_count: 4, has_lights: true, surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe"],
    description: "Indoor pickleball at Shenzhen Bay Sports Center. Leading venue for China's growing pickleball community.",
    verified: false,
  },
];

module.exports = { courts };
