const courts = [
  // === MALAYSIA ===
  {
    name: "Kenanga City Pickleball Stadium",
    slug: "kenanga-city-pickleball-stadium",
    address: "Kenanga City, Jalan Gelugor, Pudu",
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    lat: 3.1265, lng: 101.6980,
    indoor: true,
    court_count: 12,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "pro_shop", "showers", "cafe", "equipment_rental"],
    phone: "+603-9285 8888",
    website: "https://kenangacity.com.my",
    description: "Malaysia's largest indoor pickleball facility with 12 professional-grade courts. Pro shop on site, coaching available, and regular tournaments.",
    is_premium: true,
    verified: true,
  },
  {
    name: "Pickleball Hub Mont Kiara",
    slug: "pickleball-hub-mont-kiara",
    address: "1 Mont Kiara Mall, Jalan Kiara",
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    lat: 3.1690, lng: 101.6520,
    indoor: true,
    court_count: 6,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "showers", "cafe"],
    phone: "+6012-345 6789",
    description: "Popular pickleball hub inside 1 Mont Kiara mall. 6 indoor courts with air-conditioning. Beginner classes every weekend.",
    is_premium: true,
    verified: true,
  },
  {
    name: "Kuching Pickleball Centre",
    slug: "kuching-pickleball-centre",
    address: "Jalan Stampin, Kuching",
    city: "Kuching",
    state: "Sarawak",
    country: "Malaysia",
    lat: 1.5200, lng: 110.3500,
    indoor: false,
    court_count: 4,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+6082-456 789",
    description: "Kuching's first dedicated pickleball centre. Open-air courts with night lighting. Growing community of 200+ regular players.",
    is_premium: true,
    verified: true,
  },
  {
    name: "Penang Pickleball Arena",
    slug: "penang-pickleball-arena",
    address: "Jalan Sultan Azlan Shah, Bayan Lepas",
    city: "George Town",
    state: "Penang",
    country: "Malaysia",
    lat: 5.3300, lng: 100.2800,
    indoor: true,
    court_count: 8,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "showers", "pro_shop", "cafe"],
    phone: "+604-678 9012",
    description: "Penang's premier pickleball facility with 8 indoor courts. Hosts the annual Penang Open tournament.",
    is_premium: true,
    verified: true,
  },
  {
    name: "JB Pickleball Club",
    slug: "jb-pickleball-club",
    address: "Taman Sutera Utama, Skudai",
    city: "Johor Bahru",
    state: "Johor",
    country: "Malaysia",
    lat: 1.5500, lng: 103.6600,
    indoor: false,
    court_count: 6,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+6016-789 0123",
    website: "https://jbpickleball.my",
    description: "JB's largest pickleball club with 6 courts. Strong community with weekly social play and competitive leagues. Just across the causeway from Singapore — popular with SG players!",
    is_premium: false,
    verified: true,
  },
  {
    name: "Kota Kinabalu Pickleball Courts",
    slug: "kota-kinabalu-pickleball-courts",
    address: "Likas Sports Complex, Jalan Punat Tanah",
    city: "Kota Kinabalu",
    state: "Sabah",
    country: "Malaysia",
    lat: 5.9900, lng: 116.1100,
    indoor: false,
    court_count: 4,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "showers"],
    phone: "+6088-345 678",
    description: "4 outdoor pickleball courts within the Likas Sports Complex. Open to public with hourly rates. Coaching available on Saturdays.",
    verified: true,
  },
  {
    name: "Pickleball @ Desa ParkCity",
    slug: "pickleball-desa-parkcity",
    address: "The Waterfront, Desa ParkCity",
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    country: "Malaysia",
    lat: 3.1900, lng: 101.6300,
    indoor: false,
    court_count: 3,
    has_lights: false,
    surface_type: "hard",
    amenities: ["parking", "cafe"],
    description: "Community courts at Desa ParkCity's Waterfront. Free for residents, small fee for visitors. Great weekend vibe with nearby cafes.",
    verified: false,
  },
  {
    name: "Ipoh Pickleball Centre",
    slug: "ipoh-pickleball-centre",
    address: "Jalan Raja Dr Nazrin Shah, Ipoh",
    city: "Ipoh",
    state: "Perak",
    country: "Malaysia",
    lat: 4.6000, lng: 101.0800,
    indoor: true,
    court_count: 4,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+605-789 0123",
    description: "Ipoh's indoor pickleball centre. Air-conditioned with 4 courts. Beginner-friendly with paddle rental available.",
    verified: false,
  },

  // === SINGAPORE ===
  {
    name: "Singapore Pickleball Arena @ Kallang",
    slug: "singapore-pickleball-kallang",
    address: "5 Stadium Drive, Kallang",
    city: "Singapore",
    state: "Central",
    country: "Singapore",
    lat: 1.3030, lng: 103.8750,
    indoor: true,
    court_count: 10,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "showers", "pro_shop", "cafe", "equipment_rental"],
    phone: "+65 6789 0123",
    website: "https://sgpickleball.sg",
    description: "Singapore's largest indoor pickleball facility at Kallang. 10 championship-standard courts. Home of the Singapore Pickleball Open.",
    is_premium: true,
    verified: true,
  },

  // === USA (Global expansion) ===
  {
    name: "Venice Beach Pickleball Courts",
    slug: "venice-beach-pickleball",
    address: "1800 Ocean Front Walk, Venice",
    city: "Los Angeles",
    state: "California",
    country: "United States",
    lat: 33.9850, lng: -118.4730,
    indoor: false,
    court_count: 8,
    has_lights: false,
    surface_type: "hard",
    amenities: ["public_parking"],
    description: "Iconic oceanfront pickleball courts on Venice Beach. Free public courts — first come, first served. Incredible atmosphere.",
    verified: false,
  },
  {
    name: "Chicken N Pickle — Overland Park",
    slug: "chicken-n-pickle-overland-park",
    address: "5901 W 135th St, Overland Park",
    city: "Overland Park",
    state: "Kansas",
    country: "United States",
    lat: 38.8820, lng: -94.6500,
    indoor: false,
    court_count: 6,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "restaurant", "bar", "pro_shop", "equipment_rental"],
    phone: "+1-913-647-6000",
    website: "https://chickennpickle.com",
    description: "Famous pickleball-and-chicken chain. 6 outdoor courts, full restaurant + bar. Book courts online. Great for groups and parties.",
    is_premium: true,
    verified: true,
  },

  // === AUSTRALIA ===
  {
    name: "Sydney Pickleball Club",
    slug: "sydney-pickleball-club",
    address: "Perry Park, Maddox St, Alexandria",
    city: "Sydney",
    state: "NSW",
    country: "Australia",
    lat: -33.9000, lng: 151.1900,
    indoor: false,
    court_count: 6,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "equipment_rental"],
    phone: "+61-2-8000 1234",
    website: "https://sydneypickleball.com.au",
    description: "Sydney's largest pickleball club with 6 dedicated courts. All skill levels welcome. Social play Wednesdays and Saturdays.",
    verified: true,
  },

  // === UK ===
  {
    name: "Pickleball London @ Canary Wharf",
    slug: "pickleball-london-canary-wharf",
    address: "Crossrail Place, Canary Wharf",
    city: "London",
    state: "England",
    country: "United Kingdom",
    lat: 51.5050, lng: -0.0200,
    indoor: true,
    court_count: 4,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "showers", "cafe", "equipment_rental"],
    phone: "+44-20-7000 1234",
    description: "London's rooftop pickleball courts at Canary Wharf. Stunning city views. Book via app. Coaching and corporate events available.",
    verified: false,
  },

  // === MORE INTERNATIONAL COURTS (Expanded) ===
  {
    name: "Dubai Pickleball Club",
    slug: "dubai-pickleball-club",
    address: "Dubai Sports City",
    city: "Dubai",
    state: "",
    country: "United Arab Emirates",
    lat: 25.0400, lng: 55.2200,
    indoor: true,
    court_count: 6,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "pro_shop"],
    phone: "+971-4-123-4567",
    description: "Premium indoor facility in Dubai Sports City. Excellent for expats and tourists. Regular leagues and social nights.",
    is_premium: true,
    verified: true,
  },
  {
    name: "Hong Kong Pickleball Centre",
    slug: "hong-kong-pickleball-centre",
    address: "Kwun Tong, Hong Kong",
    city: "Hong Kong",
    state: "",
    country: "Hong Kong",
    lat: 22.3100, lng: 114.2200,
    indoor: true,
    court_count: 5,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "showers"],
    phone: "+852-2345-6789",
    description: "One of Hong Kong's first dedicated pickleball centres. Compact but high-quality. Very popular with the local community.",
    verified: true,
  },
  {
    name: "Auckland Pickleball Park",
    slug: "auckland-pickleball-park",
    address: "Victoria Park, Auckland",
    city: "Auckland",
    state: "",
    country: "New Zealand",
    lat: -36.8500, lng: 174.7600,
    indoor: false,
    court_count: 4,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking"],
    description: "Popular public pickleball park in the heart of Auckland. Great community atmosphere and regular weekend tournaments.",
    verified: true,
  },

  // === THAILAND ===
  {
    name: "Bangkok Pickleball Center",
    slug: "bangkok-pickleball-center",
    address: "Sukhumvit 71, Phra Khanong",
    city: "Bangkok",
    state: "Bangkok",
    country: "Thailand",
    lat: 13.7200, lng: 100.5900,
    indoor: true,
    court_count: 6,
    has_lights: true,
    surface_type: "acrylic",
    amenities: ["parking", "showers", "cafe", "equipment_rental"],
    phone: "+66-2-000 1234",
    description: "Bangkok's dedicated indoor pickleball facility. 6 air-conditioned courts. Popular with expats and locals. Coaching in English and Thai.",
    verified: false,
  },

  // === INDONESIA ===
  {
    name: "Jakarta Pickleball Courts @ GBK",
    slug: "jakarta-pickleball-gbk",
    address: "Gelora Bung Karno Complex, Senayan",
    city: "Jakarta",
    state: "DKI Jakarta",
    country: "Indonesia",
    lat: -6.2200, lng: 106.8000,
    indoor: false,
    court_count: 4,
    has_lights: true,
    surface_type: "hard",
    amenities: ["parking", "equipment_rental"],
    description: "Pickleball courts within the iconic GBK sports complex. Growing community with weekend tournaments.",
    verified: false,
  },
];

module.exports = { courts };
